spring:
  main.allow-bean-definition-overriding: true
  # 自定义的主数据源配置信息
  primary:
    datasource:
      #使用druid连接池
      type: com.alibaba.druid.pool.DruidDataSource
      #       Oracle数据库
      druid:
        driver-class-name: oracle.jdbc.driver.OracleDriver
        url: jdbc:oracle:thin:@127.0.0.1:1521/orcl
        username: shiny
        password: shiny
# MyBatis
mybatis:
  # 搜索指定包别名
  typeAliasesPackage: com.suncreate
  # 配置mapper的扫描，找到所有的mapper.xml映射文件
  mapperLocations: classpath*:mappers/repository/**/*Mapper.xml
  # 加载全局的配置文件
  configLocation: classpath:mybatis-config.xml

#开启事物
transaction:
  rollback-on-commit-failure: true
pagehelper:
   # helperDialect: oracle                          #分页插件方言选择 oralce数据库
    helperDialect: mysql                          #分页插件方言选择 mysql数据库
    reasonable: true                               #合理化参数，设为true时pageNum<=0 时会查第一页， pageNum>pages（超过总数时），会查询最后一页
    supportMethodsArguments: true
